### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sherter** [sherter/google-java-format-gradle-plugin#1]
Collecting some ideas...
- [x] [50a893e02ef6ac42f9852cb42fc3f488aadbaf67] Add a [VertificationTask](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/VerificationTask.html) to check whether Java sources are formatted correctly
- [x] Possibility to exclude specific files or add files that are not in a [JavaSourceSet](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSet.html) (extended [SourceTask](https://docs.gradle.org/2.0/javadoc/org/gradle/api/tasks/SourceTask), see [specifying input fies](https://docs.gradle.org/2.0/userguide/working_with_files.html#sec:specifying_multiple_files))
- [x] [dd23d4d033a7ef3d37a116a4f0ead293e70d884e] Proper UP-TO-DATE check
- [x] [ba7e8c6af96ff5fa4de1aef6f70810b86a64f68b] Delay reading states database; don't do it in configuration phase!
- [x] Update Readme with new features
